name: steam_totp
description: A Dart library for generating 5-character alphanumeric Steam TOTP codes.
version: 0.0.2
repository: https://github.com/elliotwutingfeng/steam_totp
funding:
 - https://www.buymeacoffee.com/elliotwutingfeng
topics:
  - crypto
  - cryptography
  - mfa
  - otp
  - security

environment:
  sdk: ^3.4.0

dependencies:
  base32: ^2.1.3
  hashlib: ^1.20.4

dev_dependencies:
  coverage: ^1.9.2
  lints: ^4.0.0
  test: ^1.25.8
