name: steam_totp
description: A Dart library for generating 5-character alphanumeric Steam TOTP codes.
version: 0.0.1
repository: https://github.com/elliotwutingfeng/steam_totp
funding:
 - https://www.buymeacoffee.com/elliotwutingfeng
topics:
  - crypto
  - cryptography
  - mfa
  - otp
  - security

environment:
  sdk: ^3.0.0

dependencies:
  base32: ^2.1.3
  hashlib: ^1.13.0

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  test: ^1.25.3
